### ISSUE TITLE
Can't use the example on web 

### ISSUE THREAD

**Issue by Nandez89** [stermedia/react-web-gifted-chat#2]
#### Issue Description

When adding the component to a react app the app fails to compile and shows this error message:
./node_modules/react-web-gifted-chat/node_modules/react-native-parsed-text/src/ParsedText.js
Module parse failed: Unexpected token (13:2)
You may need an appropriate loader to handle this file type.
| 
| const defaultParseShape = React.PropTypes.shape({
|   ...ReactNative.Text.propTypes,
|   type: React.PropTypes.oneOf(Object.keys(PATTERNS)).isRequired,
| });

#### Steps to Reproduce / Code Snippets

do the npm install and add a component to a page on your react app

#### Expected Results

should render the component

#### Additional Information

* React Native version: There's no react native? this is a react web app
* react-native-gifted-chat version: react-native-gifted-chat? "react-web-gifted-chat": "0.0.4"
* Platform(s) (iOS, Android, or both?): Doesn't apply this is a web component.

**Comment by txs** [comment]
You might use the latest react, so you have to import PropTypes as a standalone package

**Comment by c-goettert** [comment]
I had the same issue. It's `react-native-parsed-text` causing this issues because it's using the Object-spread syntax as shown in the error (`...ReactNative.Text.propTypes`), which is obviously not compiled by babel in your Project. You need to configure webpack so it compiles the module. If you created your App using [create-react-app](https://github.com/facebook/create-react-app), there is no way to configure webpack directly. You either have to `eject` the project, or use [react-app-rewired](https://github.com/timarney/react-app-rewired) to do so. 
Then, in webpack-config you need to add the module path of `react-native-parsed-text` to the babel-loader 'includes'-property. Something like this:
```
// webpack-config:
...
{
  test: /\.(js|jsx|mjs)$/,
  include: [
    paths.appSrc,
    'YOUR-PROJECT-PATH/node_modules/react-native-parsed-text'
  ],
  loader: require.resolve('babel-loader')
},
...
```
If your using react-app-rewired, your `config-overrides.js` might look something like this (didn't test):
```
const { getBabelLoader } = require('react-app-rewired')
const fs = require('fs')
const path = require('path')

const appDirectory = fs.realpathSync(process.cwd())
const resolveApp = relativePath => path.resolve(appDirectory, relativePath)

/* config-overrides.js */
module.exports = function override (config, env) {
  const babelLoader = getBabelLoader(config.module.rules)
  babelLoader.include = [resolveApp('src'), resolveApp('node_modules/react-native-parsed-text')]
  return config
}

```

Note: Unfortunately, after this step I got to [issue#1](https://github.com/stermedia/react-web-gifted-chat/issues/1).

**Comment by johniak** [comment]
Yeah, it was broken, in the next upgrade it will be working, I also fixed example, this is already on repository, but it's not pushed to npm, it also contains new react version
